<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MinecraftLauncherPerso</RootNamespace>
    <AssemblyName>MinecraftLauncherPerso</AssemblyName>
    <Platforms>x64</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Gère l'installation de Forge et le lancement du jeu (classpath, arguments JVM/jeu). -->
    <PackageReference Include="CmlLib.Core" Version="3.3.4" />
  </ItemGroup>

</Project>
